kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: malicious-detection-hpa
spec:
    hosts:
    - 127.0.0.1
    scaleTargetRef:
        name: malicious-detection
        kind: Deployment
        apiVersion: apps/v1
        service: malicious-detection
        port: 80
    replicas:
        min: 2
        max: 15
    targetPendingRequests: 100