kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: malicious-detection
spec:
  hosts:
  - "localhost"
  targetPendingRequests: 100
  scaleTargetRef:
    name: malicious-detection
    kind: Deployment
    apiVersion: apps/v1
    service: malicious-detection
    port: 30070
  replicas:
    min: 2
    max: 15