apiVersion: apps/v1
kind: Deployment
metadata:
  name: malicious-detection
  labels:
    app: malicious-detection-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: malicious-detection-app
  template:
    metadata:
      labels:
        app: malicious-detection-app
    spec:
      containers:
      - name: malicious-detection
        image: prg10/malicious_url_detection_v2
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"

---
apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: malicious-detection
  namespace: default
spec:
  type: LoadBalancer
  selector:
    # Selector for Pods
    app: malicious-detection-app
  ports:
  # Port Map
  - port: 8501
    targetPort: 8501
    nodePort: 30080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: securl-ingress
  annotations:
     appprotectdos.f5.com/app-protect-dos-resource: "default/dos-protected"
spec:
  ingressClassName: nginx
  rules:
    - host: "localhost"
      http:
        paths:
          - backend:
              service:
                name: malicious-detection
                port:
                  number: 30070
            path: /
            pathType: Prefix