apiVersion: appprotectdos.f5.com/v1beta1
kind: DosProtectedResource
metadata:
  name: dos-protected
spec:
  enable: true
  name: "malicious-detection"
  apDosMonitor:
     uri: 127.0.0.1:30070
  apDosPolicy: "default/dospolicy"
  dosSecurityLog:
     enable: true
     apDosLogConf: "doslogconf"
     dosLogDest: "syslog-svc.default.svc.cluster.local:514"
